[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.36"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
bytecode_hash = "ipfs"
deny = "warnings"

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 64
fail_on_revert = false

[lint]
lint_on_build = false
severity = ["high", "medium"]
exclude_lints = ["block-timestamp"]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"

[rpc_endpoints]
base = "${BASE_RPC_URL}"
